__title__ = 'num_fh'
__version__ = '1.1.0'
__summary__ = 'numeric fused-head identification and resolution'
__uri__ = 'http://nlp.biu.ac.il/~lazary/fh/'
__author__ = 'Yanai Elazar and Yoav Goldberg'
__email__ = 'yanaiela@gmail.com'
__license__ = 'MIT'